# Author: Fabi Liria
name: CI/CD Pipeline

on:
  push:
    branches:
      - Development
      - QA
      - Production
  pull_request:
    branches:
      - Development
      - QA
      - Production

jobs:
  check-package-json:
    runs-on: ubuntu-latest
    outputs:
      has_package_json: ${{ steps.check.outputs.has_package_json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for package.json
        id: check
        run: |
          if [ -f package.json ]; then
            echo "has_package_json=true" >> $GITHUB_ENV
          else
            echo "has_package_json=false" >> $GITHUB_ENV
          fi

  setup:
    runs-on: ubuntu-latest
    needs: check-package-json
    if: ${{ needs.check-package-json.outputs.has_package_json == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: check-package-json
    if: ${{ needs.check-package-json.outputs.has_package_json == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: check-package-json
    if: ${{ needs.check-package-json.outputs.has_package_json == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    if: ${{ needs.check-package-json.outputs.has_package_json == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/Production'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  security:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run CodeQL analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}