# Author: Fabi Liria
name: CI Development

on:
  push:
    branches:
      - Development

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should_create_pr: ${{ steps.check.outputs.should_create_pr }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit message
        id: check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -q "QA transition:"; then
            echo "should_create_pr=true" >> $GITHUB_ENV
            echo "::set-output name=should_create_pr::true"
          else
            echo "should_create_pr=false" >> $GITHUB_ENV
            echo "::set-output name=should_create_pr::false"
          fi

  create-pull-request:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.should_create_pr == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request to QA
        run: gh pr create -B QA -H Development --title 'Automated PR from Development to QA' --body 'This is an automated pull request created from the Development branch to QA.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
