# Author: Fabi Liria
name: CI QA

on:
  push:
    branches:
      - QA

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should_create_pr: ${{ steps.check.outputs.should_create_pr }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit message
        id: check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -q "Production transition:"; then
            echo "::set-output name=should_create_pr::true"
          else
            echo "::set-output name=should_create_pr::false"
          fi

  create-pull-request:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.should_create_pr == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to Production
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: Production
          branch: QA
          title: "Automated PR from QA to Production"
          body: "This is an automated pull request created from the QA branch to Production."