# Author: Fabi Liria
name: CI QA

on:
  push:
    branches:
      - QA

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should_create_pr: ${{ steps.check.outputs.should_create_pr }}
      commit_details: ${{ steps.check.outputs.commit_details }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit message
        id: check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -q "Production transition:"; then
            COMMIT_DETAILS=$(echo "$COMMIT_MESSAGE" | sed -n 's/.*Production transition: \(.*\)/\1/p')
            echo "should_create_pr=true" >> $GITHUB_ENV
            echo "::set-output name=should_create_pr::true"
            echo "::set-output name=commit_details::$COMMIT_DETAILS"
          else
            echo "should_create_pr=false" >> $GITHUB_ENV
            echo "::set-output name=should_create_pr::false"
            echo "::set-output name=commit_details::"
          fi

  create-pull-request:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.should_create_pr == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request to Production
        run: |
          BODY="This is an automated pull request created from the QA branch to Production.

          Details:
          ${{ needs.check-commit-message.outputs.commit_details }}"
          gh pr create -B Production -H QA --title 'Automated PR from QA to Production' --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}