name: CI QA

on:
  push:
    branches:
      - QA

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node.js deprecation warning flag
        run: |
          echo 'NODE_OPTIONS=--no-deprecation' >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Create Pull Request to QA
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: QA
          title: "Automated PR from QA to Main"
          body: "This is an automated pull request created from the QA branch to Main."
